events {}

http {
    server {
        listen 80;

        # Route to Frontend (Port 3000)
        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route to User Service (Port 3001)
        # Now, any request to http://localhost/users goes here
        location /users {
            proxy_pass http://user-service:3001;
            proxy_set_header Host $host;
        }
    }
}