events {}

http {
    server {
        listen 80;

        # Route to Frontend (Port 3000)
        location / {
            proxy_pass http://frontend:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route to User Service (Port 3001)
        # Now, any request to http://localhost/users/ goes here
        location /user/ {
            proxy_pass http://user-service:3001;
            proxy_set_header Host $host;
        }

        # Route to Question Service (Port 3003)
        # Now, any request to http://localhost/questions/ goes here
        # location /questions/ {
        #     proxy_pass http://question-service:3003;
        #     proxy_set_header Host $host;
        # }
    }
}