FROM node:22-alpine AS builder
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Build the app
COPY . .
RUN npx tsc

# Production image
FROM node:22-alpine
WORKDIR /usr/src/app

# Install only production dependencies
COPY package*.json ./
RUN npm install --production

# Copy built files from builder
COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 3005
CMD ["node", "dist/index.js"]
